# Generated by Django 3.1 on 2024-09-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='contacto',
            field=models.IntegerField(max_length=20, verbose_name='contacto'),
        ),
    ]
